version: '3.8'

services:
  web:
    build: .
    container_name: web
    volumes: 
      - .:/app
      # - ./staticfiles:/app/staticfiles
      - ./static:/app/static 
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    # environment:
    #   - DEBUG=True
    #   - DB_NAME=shoe_spectra_pjt
    #   - DB_USER=postgres
    #   - DB_PASSWORD=admin123
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - SECRET_KEY=django-insecure-v9zfx2ugz#h+y^m1i!p-=a3efyi55ra&&_1$i-83_so*t0@rpd
    #   - GOOGLE_CLIENT_ID="1026950511350-h4a1dik27uugqja7oe1qhstml3kc0hjh.apps.googleusercontent.com" 
    #   - GOOGLE_SECRET_KEY="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"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=shoe_spectra_pjt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5434:5432"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  staticfiles:
