version: '3.8'

services:
  web:
    build: .
    container_name: web
    volumes: 
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - shoespectra-network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=shoe_spectra_pjt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shoespectra-network

volumes:
  postgres_data:
  staticfiles:

networks:
  shoespectra-network:
    driver: bridge
