# Generated by Django 5.0.7 on 2024-07-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
