# Generated by Django 5.0.7 on 2024-08-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
