# Generated by Django 5.0.7 on 2024-08-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
