# Generated by Django 5.0.7 on 2024-08-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_variantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
