# Generated by Django 5.0.7 on 2024-08-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_remove_product_shoe_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
