# Generated by Django 5.0.7 on 2024-08-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_productsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
