# Generated by Django 5.0.7 on 2024-08-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='admin_app.order')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.productsize')),
            ],
        ),
    ]
