# Generated by Django 5.0.7 on 2024-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0037_address_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
