# Generated by Django 5.0.7 on 2024-08-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0038_orderaddress_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='recipient_name',
        ),
    ]
