# Generated by Django 5.0.7 on 2024-08-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0040_address_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity',
        ),
    ]
