# Generated by Django 5.0.7 on 2024-08-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0043_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
