# Generated by Django 5.0.7 on 2024-08-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0046_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_success',
            field=models.BooleanField(default=False),
        ),
    ]
